### ISSUE TITLE
5折交叉验证

### ISSUE THREAD

**Issue by Donaghys** [xiaoxiaokuaile/2022DCIC_OCR#1]
感谢作者的贡献，新手学习下这个5折交叉验证，请问这个生成csv文件有个原始训练集图片路径和测试集图片路径，您是将所有训练集图片生成一个csv文件，那这个测试集图片就是官方提供的A榜验证集吗？

**Comment by xiaoxiaokuaile** [comment]
五折交叉就是给训练集15000张图片拆成5份，分别为fold0,1,2,3,4, 写进csv文件中，4份训练1份验证，readme里面的分数是线下验证分数,线下验证分数是比线上验证分数低2个千分点左右的，线下0.974线上就能有0.976+这样子。csv文件制作代码在tool code/data里面，你可以找找。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoxiaokuaile/2022DCIC_OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 下午2:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiaoxiaokuaile/2022DCIC_OCR] 5折交叉验证 (Issue #1)





 
感谢作者的贡献，新手学习下这个5折交叉验证，请问这个生成csv文件有个原始训练集图片路径和测试集图片路径，您是将所有训练集图片生成一个csv文件，那这个测试集图片就是官方提供的A榜验证集吗？
